name: Playwright Full Test Suite

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: 🔧 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run API Auth Setup
        run: npx tsx Task3/utils/setup.ts

      - name: Run Playwright API Tests
        run: npx tsx ./Task3/utils/setup.ts
        run: npx playwright test --project=API --workers=1

      - name: Run Playwright Web Tests
        run: npx playwright test web.spec.ts

      - name: Upload HTML Test Report (if failure)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
