name: Playwright Full Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Run Playwright Web Tests
        # we add the html reporter so that playwright writes out an HTML report
        run: npx playwright test web.spec.ts \
               --project="Web - Chromium" \
               --reporter=html

      - name: Upload HTML Test Report
        # always upload the generated report directory
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
